import { describe, it, expect, beforeEach, vi } from 'vitest';
import { Game } from '../../src/core/Game';
import { Player } from '../../src/core/Player';
import { ConversationLog } from '../../src/core/ConversationLog';
import { PlayerStatus, type PlayerId } from '../../src/interfaces/IPlayer';
import { RoleName } from '../../src/interfaces/IRole';
import type { IAgent, PlayerAction } from '../../src/interfaces/IAgent';
import type { IRole } from '../../src/interfaces/IRole';
import { MessageVisibility } from '../../src/interfaces/IMessage';
import { InitializationPhase } from '../../src/phases/InitializationPhase';
import { GameOverPhase } from '../../src/phases/GameOverPhase';

// Mock role implementations
const mockVillagerRole: IRole = {
    name: RoleName.Villager,
    allegiance: 'Town',
    canPerformNightAction: false,
    description: 'A simple villager',
};

const mockMafiaRole: IRole = {
    name: RoleName.Mafia,
    allegiance: 'Mafia',
    canPerformNightAction: true,
    description: 'Mafia member',
};

// Mock agent factory
const createMockAgent = (id: PlayerId): IAgent => ({
    playerId: id,
    getAction: vi.fn().mockResolvedValue({ type: 'noAction' } as PlayerAction)
});

// Mock renderer (optional, but good practice)
const mockRenderer = {
    renderGameStart: vi.fn(),
    renderRoundStart: vi.fn(),
    renderPhaseStart: vi.fn(),
    renderMessage: vi.fn(),
    renderVoteResults: vi.fn(),
    renderNightResults: vi.fn(),
    renderPlayerStatusUpdate: vi.fn(),
    renderGameOver: vi.fn(),
    renderNarration: vi.fn(),
    getConversationLog: vi.fn().mockReturnValue([]),
};

describe('Game', () => {
    let playerNames: string[];
    let agents: IAgent[];
    let playerSetups: { name: string; agent: IAgent; role: IRole }[];
    let game: Game;

    // Variables to hold the *actual* IDs generated by the Game constructor
    let villager1Id: PlayerId;
    let villager2Id: PlayerId;
    let villager3Id: PlayerId;
    let mafia1Id: PlayerId;
    let mafia2Id: PlayerId;
    let allPlayerIds: PlayerId[];

    // Helper to get a player's agent mock using the *actual* ID
    const getAgentMock = (playerId: PlayerId) => {
       const player = game.getPlayer(playerId);
       if (!player) throw new Error(`Player ${playerId} not found in test setup (getAgentMock)`);
       return player.agent.getAction as ReturnType<typeof vi.fn>;
    }

    beforeEach(() => {
        // Reset mocks
        vi.clearAllMocks();

        // Define player names
        playerNames = ['Villager 1', 'Villager 2', 'Villager 3', 'Mafia 1', 'Mafia 2'];

        // Create mock agents (IDs are temporary placeholders)
        agents = [
            createMockAgent('temp-v1'),
            createMockAgent('temp-v2'),
            createMockAgent('temp-v3'),
            createMockAgent('temp-m1'),
            createMockAgent('temp-m2'),
        ];

        // Define player setups
        playerSetups = [
            { name: playerNames[0], role: mockVillagerRole, agent: agents[0] },
            { name: playerNames[1], role: mockVillagerRole, agent: agents[1] },
            { name: playerNames[2], role: mockVillagerRole, agent: agents[2] },
            { name: playerNames[3], role: mockMafiaRole,    agent: agents[3] },
            { name: playerNames[4], role: mockMafiaRole,    agent: agents[4] },
        ];

        // Create the game - this will generate the actual IDs
        game = new Game(playerSetups);
        game.addRenderer(mockRenderer);

        // --- Retrieve the ACTUAL Player IDs generated by the Game --- 
        const actualPlayers = Array.from(game.getPlayers().values());
        villager1Id = actualPlayers.find(p => p.name === playerNames[0])!.id;
        villager2Id = actualPlayers.find(p => p.name === playerNames[1])!.id;
        villager3Id = actualPlayers.find(p => p.name === playerNames[2])!.id;
        mafia1Id = actualPlayers.find(p => p.name === playerNames[3])!.id;
        mafia2Id = actualPlayers.find(p => p.name === playerNames[4])!.id;
        allPlayerIds = [villager1Id, villager2Id, villager3Id, mafia1Id, mafia2Id];

        // --- Verify agents have been assigned the correct IDs by the constructor --- 
        expect(game.getPlayer(villager1Id)?.agent.playerId).toBe(villager1Id);
        expect(game.getPlayer(mafia1Id)?.agent.playerId).toBe(mafia1Id);
    });

    describe('Game initialization', () => {
        it('should initialize with a unique ID', () => {
            expect(game.id).toBeDefined();
            expect(typeof game.id).toBe('string');
        });

        it('should start at round 0 and in Initialization phase', () => {
            expect(game.round).toBe(0);
            expect(game.getCurrentPhaseType()).toBe('Init');
        });

        it('should initialize with the correct players and statuses', () => {
            const playersMap = game.getPlayers();
            expect(playersMap.size).toBe(5);

            // Check Villager 1 using the retrieved actual ID
            const p1 = game.getPlayer(villager1Id);
            expect(p1).toBeDefined();
            expect(p1?.name).toBe(playerNames[0]);
            expect(p1?.role.name).toBe(RoleName.Villager);
            expect(p1?.status).toBe(PlayerStatus.Alive);
            expect(p1?.agent.playerId).toBe(villager1Id); 

            // Check Mafia 1 using the retrieved actual ID
            const p4 = game.getPlayer(mafia1Id);
            expect(p4).toBeDefined();
            expect(p4?.name).toBe(playerNames[3]);
            expect(p4?.role.name).toBe(RoleName.Mafia);
            expect(p4?.status).toBe(PlayerStatus.Alive);
            expect(p4?.agent.playerId).toBe(mafia1Id);

            playersMap.forEach(player => {
                expect(player.isAlive()).toBe(true);
            });
        });

        it('should throw error if fewer than 3 players are provided', () => {
             const fewPlayerSetups = [
                { name: 'P1', agent: createMockAgent('t1'), role: mockVillagerRole }, 
                { name: 'P2', agent: createMockAgent('t2'), role: mockMafiaRole }
             ];
             expect(() => new Game(fewPlayerSetups)).toThrow(/Not enough players/);
         });
    });

    describe('Player Accessors', () => {
        it('should get a player by ID', () => {
            const player = game.getPlayer(villager1Id);
            expect(player).toBeDefined();
            expect(player?.id).toBe(villager1Id);
            expect(player?.name).toBe(playerNames[0]);
        });

        it('should return undefined for non-existent player ID', () => {
            const player = game.getPlayer('non-existent-id');
            expect(player).toBeUndefined();
        });

        it('should get all alive players', () => {
            let alivePlayers = game.getAlivePlayers();
            expect(alivePlayers.length).toBe(5);

            // Kill a player using the actual ID and check again
            game.killPlayer(villager1Id, "test kill");
            alivePlayers = game.getAlivePlayers();
            expect(alivePlayers.length).toBe(4);
            expect(alivePlayers.find(p => p.id === villager1Id)).toBeUndefined();
        });

        it('should get alive Mafia', () => {
            let aliveMafia = game.getAliveMafia();
            expect(aliveMafia.length).toBe(2);
            // Check using actual IDs
            expect(aliveMafia.map(p => p.id)).toEqual(expect.arrayContaining([mafia1Id, mafia2Id]));

            // Kill using actual ID
            game.killPlayer(mafia1Id, "test kill");
            aliveMafia = game.getAliveMafia();
             expect(aliveMafia.length).toBe(1);
             expect(aliveMafia[0].id).toBe(mafia2Id);
        });

         it('should get alive Villagers', () => {
             let aliveVillagers = game.getAliveVillagers();
             expect(aliveVillagers.length).toBe(3);
             // Check using actual IDs
             expect(aliveVillagers.map(p => p.id)).toEqual(expect.arrayContaining([villager1Id, villager2Id, villager3Id]));

             // Kill using actual ID
             game.killPlayer(villager1Id, "test kill");
             aliveVillagers = game.getAliveVillagers();
             expect(aliveVillagers.length).toBe(2);
             expect(aliveVillagers.map(p => p.id)).toEqual(expect.arrayContaining([villager2Id, villager3Id]));
         });

        it('should get public player map', () => {
             const publicMap = game.getPublicPlayerMap();
             expect(publicMap.size).toBe(5);
             // Check using actual ID
             const p1Public = publicMap.get(villager1Id);
             expect(p1Public).toEqual({ id: villager1Id, name: playerNames[0], status: PlayerStatus.Alive });
             expect(p1Public).not.toHaveProperty('role');
         });

          it('should get public player array', () => {
             const publicArray = game.getPublicPlayerArray();
             expect(publicArray.length).toBe(5);
             // Check using actual ID
             const p1Public = publicArray.find(p => p.id === villager1Id);
             expect(p1Public).toEqual({ id: villager1Id, name: playerNames[0], status: PlayerStatus.Alive });
             expect(p1Public).not.toHaveProperty('role');
         });
    });

     describe('Game State Visibility (generateVisibleGameState)', () => {
         it('should generate correct state for a Villager', () => {
             // Manually set state for testing (REMOVED - Use actual initial state)
             // game["#round"] = 1; 
             // game["#currentState"] = { type: 'Day', runPhase: vi.fn(), transition: vi.fn() } as any;

             // Use actual villager ID
             const state = game.generateVisibleGameState(villager1Id);

             expect(state.gameId).toBe(game.id);
             expect(state.round).toBe(0); // Check initial round
             expect(state.phase).toBe('Init'); // Check initial phase
             expect(state.self.id).toBe(villager1Id);
             expect(state.self.name).toBe(playerNames[0]);
             expect(state.self.role).toBe(RoleName.Villager);
             expect(state.self.isMafia).toBe(false);
             expect(state.players.length).toBe(5);
             // Check player info using actual ID
             expect(state.players.find(p => p.id === villager1Id)).toEqual({ id: villager1Id, name: playerNames[0], status: PlayerStatus.Alive });
             expect(state.alivePlayerIds.size).toBe(5);
             expect(state.mafiaPlayerIds).toBeUndefined(); 
         });

         it('should generate correct state for a Mafia member', () => {
             // Manually set state for testing (REMOVED - Use actual initial state)
             // game["#round"] = 1;
             // game["#currentState"] = { type: 'Night', runPhase: vi.fn(), transition: vi.fn() } as any; 

             // Use actual mafia ID
             const state = game.generateVisibleGameState(mafia1Id);

             expect(state.gameId).toBe(game.id);
             expect(state.round).toBe(0); // Check initial round
             expect(state.phase).toBe('Init'); // Check initial phase
             expect(state.self.id).toBe(mafia1Id);
             expect(state.self.name).toBe(playerNames[3]);
             expect(state.self.role).toBe(RoleName.Mafia);
             expect(state.self.isMafia).toBe(true);
             expect(state.players.length).toBe(5);
             expect(state.alivePlayerIds.size).toBe(5);
             expect(state.mafiaPlayerIds).toBeDefined();
             expect(state.mafiaPlayerIds?.size).toBe(2); 
             expect(state.mafiaPlayerIds).toContain(mafia1Id);
             expect(state.mafiaPlayerIds).toContain(mafia2Id);
         });

        it('should reflect dead players in generated state', () => {
             // Kill using actual IDs
             game.killPlayer(villager1Id, 'killed');
             game.killPlayer(mafia2Id, 'killed'); // Kill one mafia

             // Manually set state for testing
             game["#round"] = 2;
             game["#currentState"] = { type: 'Day', runPhase: vi.fn(), transition: vi.fn() } as any;

             // Generate state for remaining mafia member using actual ID
             const state = game.generateVisibleGameState(mafia1Id); 

             expect(state.alivePlayerIds.size).toBe(3);
             expect(state.alivePlayerIds).not.toContain(villager1Id);
             expect(state.alivePlayerIds).not.toContain(mafia2Id);
             expect(state.mafiaPlayerIds).toBeDefined();
             expect(state.mafiaPlayerIds?.size).toBe(1); // Only sees self now
             expect(state.mafiaPlayerIds).toContain(mafia1Id);

             // Check public info reflects death using actual IDs
             const p1Info = state.players.find(p => p.id === villager1Id);
             expect(p1Info?.status).toBe(PlayerStatus.Dead);
             const p5Info = state.players.find(p => p.id === mafia2Id);
             expect(p5Info?.status).toBe(PlayerStatus.Dead);
             const p2Info = state.players.find(p => p.id === villager2Id);
             expect(p2Info?.status).toBe(PlayerStatus.Alive);
         });
     });

    describe('Win conditions (checkWinCondition)', () => {
        it('should return "Town" when all Mafia are eliminated', () => {
            // Kill using actual IDs
            game.killPlayer(mafia1Id, "executed");
            game.killPlayer(mafia2Id, "killed");
            expect(game.checkWinCondition()).toBe('Town');
        });

        it('should return "Mafia" when Mafia count equals Town count', () => {
            // Kill using actual ID
            game.killPlayer(villager1Id, "killed"); // 2 Town, 2 Mafia
            expect(game.checkWinCondition()).toBe('Mafia');
        });

        it('should return "Mafia" when Mafia count exceeds Town count', () => {
             // Kill using actual IDs
            game.killPlayer(villager1Id, "killed"); // 2 Town, 2 Mafia
            game.killPlayer(villager2Id, "executed"); // 1 Town, 2 Mafia
            expect(game.checkWinCondition()).toBe('Mafia');
        });

        it('should return null when neither win condition is met', () => {
            // Start: 3 Town, 2 Mafia
            expect(game.checkWinCondition()).toBeNull();
             // Kill using actual ID
            game.killPlayer(mafia2Id, "killed"); // 3 Town, 1 Mafia
             expect(game.checkWinCondition()).toBeNull();
         });

        it('should handle edge case of 1v1 (Mafia win)', () => {
             // Kill using actual IDs
             game.killPlayer(villager1Id, "killed");
             game.killPlayer(villager2Id, "killed"); // 1 Town, 2 Mafia
             game.killPlayer(mafia1Id, "executed"); // 1 Town, 1 Mafia
             expect(game.checkWinCondition()).toBe('Mafia');
         });

        it('should handle edge case of 1v0 (Town win)', () => {
             // Kill using actual IDs
             game.killPlayer(villager1Id, "killed");
             game.killPlayer(villager2Id, "killed"); 
             game.killPlayer(mafia1Id, "executed"); 
             game.killPlayer(mafia2Id, "killed"); // 1 Town, 0 Mafia
             expect(game.checkWinCondition()).toBe('Town');
         });
    });

    describe('Game Flow (Simplified - testing state transitions indirectly)', () => {
         it('should eventually reach GameOverPhase when win condition is met', async () => {
             // Mock agents using actual IDs
             const mafiaAgent1 = getAgentMock(mafia1Id);
             const mafiaAgent2 = getAgentMock(mafia2Id);
             const villagerAgent1 = getAgentMock(villager1Id);
             const villagerAgent2 = getAgentMock(villager2Id);
             const villagerAgent3 = getAgentMock(villager3Id);

             // Night 1: Mafia kill Villager 1 (V1 dies) -> Alive: V2, V3, M1, M2
             mafiaAgent1.mockResolvedValue({ type: 'mafiaKill', targetPlayerId: villager1Id });
             mafiaAgent2.mockResolvedValue({ type: 'mafiaKill', targetPlayerId: villager1Id }); 
             // Day 1: V2, V3, M2 vote for M1 (M1 executed) -> Alive: V2, V3, M2
             // Assuming majority of 4 living players = 3 votes needed
             villagerAgent2.mockResolvedValue({ type: 'vote', targetPlayerId: mafia1Id });
             villagerAgent3.mockResolvedValue({ type: 'vote', targetPlayerId: mafia1Id });
             mafiaAgent2.mockResolvedValue({ type: 'vote', targetPlayerId: mafia1Id }); // M2 votes M1

             // Night 2: M2 kills Villager 2 (V2 dies) -> Alive: V3, M2 (1 Town vs 1 Mafia)
             mafiaAgent2.mockResolvedValue({ type: 'mafiaKill', targetPlayerId: villager2Id });
             // Day 2: (Game likely ends here as Mafia >= Town)
             villagerAgent3.mockResolvedValue({type: 'vote', targetPlayerId: mafia2Id});

             await game.runGameLoop();

             // Check final state - Expect Mafia Win due to 1v1 condition
             expect(game.getCurrentPhaseType()).toBe('GameOver');
             expect(mockRenderer.renderGameOver).toHaveBeenCalledWith('Mafia', expect.anything());
         });
    });

    describe('Logging Messages (logMessage)', () => {
         it('should add a public message to the log and notify renderer', () => {
             const content = "Public announcement";
             const message = game.logMessage(null, content, MessageVisibility.Public);

             expect(message.senderId).toBeNull();
             expect(message.senderName).toBe('System'); // Correctly system
             expect(message.content).toBe(content);
             expect(message.visibility).toBe(MessageVisibility.Public);
             expect(message.phase).toBe(game.getCurrentPhaseType()); 
             expect(message.round).toBe(game.round); 

             const log = game.getConversationLog().getAllMessages();
             expect(log).toContain(message);
             expect(mockRenderer.renderMessage).toHaveBeenCalledWith(message);
         });

         it('should add a player message to the log and notify renderer if public', () => {
             const senderId = villager1Id; // Use actual ID
             const content = "Hello!";
             const message = game.logMessage(senderId, content, MessageVisibility.Public);

             expect(message.senderId).toBe(senderId);
             expect(message.senderName).toBe(playerNames[0]); // Check against correct name
             expect(message.content).toBe(content);
             expect(message.visibility).toBe(MessageVisibility.Public);

             const log = game.getConversationLog().getAllMessages();
             expect(log).toContain(message);
             expect(mockRenderer.renderMessage).toHaveBeenCalledWith(message);
         });

          it('should add a Mafia message to the log and notify renderer (simple approach)', () => {
              const senderId = mafia1Id; // Use actual ID
              const content = "Mafia secret";
              // REMOVED manual state setting - Use phaseOverride instead
              // game["#currentState"] = { type: 'Night', runPhase: vi.fn(), transition: vi.fn() } as any;
              const message = game.logMessage(senderId, content, MessageVisibility.Mafia, 'Night'); // Use phaseOverride

              expect(message.senderId).toBe(senderId);
              expect(message.senderName).toBe(playerNames[3]); // Check against correct name
              expect(message.content).toBe(content);
              expect(message.visibility).toBe(MessageVisibility.Mafia);
              expect(message.phase).toBe('Night'); // Check overridden phase

              const log = game.getConversationLog().getAllMessages();
              expect(log).toContain(message);
              expect(mockRenderer.renderMessage).toHaveBeenCalledWith(message);
          });

         it('should allow overriding the phase in the log', () => {
             const content = "Message logged late";
             const message = game.logMessage(null, content, MessageVisibility.Public, 'Night'); 

             expect(message.phase).toBe('Night');
             expect(game.getCurrentPhaseType()).not.toBe('Night'); 
         });
     });

    describe('Killing Players (killPlayer)', () => {
         it('should set player status to Dead', () => {
             const playerIdToKill = villager1Id; // Use actual ID
             const player = game.getPlayer(playerIdToKill);
             expect(player?.status).toBe(PlayerStatus.Alive);

             game.killPlayer(playerIdToKill, "was killed for testing");

             // Fetch player again to check updated status
             expect(game.getPlayer(playerIdToKill)?.status).toBe(PlayerStatus.Dead);
         });

         it('should log a public message about the death', () => {
              const playerIdToKill = villager1Id; // Use actual ID
              const player = game.getPlayer(playerIdToKill);
              expect(player).toBeDefined(); // Ensure player exists before proceeding
              const reason = "was eliminated";
              game.killPlayer(playerIdToKill, reason);

              const log = game.getConversationLog().getAllMessages();
              // Check for content based on the player's actual name and role
              const expectedContent = `${player!.name} (${player!.role.name}) ${reason}`;
              const killMessage = log.find(m => m.content === expectedContent);
              expect(killMessage).toBeDefined();
              expect(killMessage?.visibility).toBe(MessageVisibility.Public);
              expect(killMessage?.content).toBe(expectedContent);
          });

         it('should notify renderers about the status update', () => {
             const playerIdToKill = villager1Id; // Use actual ID
             const player = game.getPlayer(playerIdToKill);
             expect(player).toBeDefined();
             const publicInfoBeforeKill = player!.getPublicRepresentation(); // Get info BEFORE kill
             expect(publicInfoBeforeKill.status).toBe(PlayerStatus.Alive); // Verify assumption

             game.killPlayer(playerIdToKill, "was killed");

             // Player status is Dead *after* killPlayer runs
             const publicInfoAfterKill = game.getPlayer(playerIdToKill)?.getPublicRepresentation();
             expect(publicInfoAfterKill?.status).toBe(PlayerStatus.Dead); // Verify assumption

             expect(mockRenderer.renderPlayerStatusUpdate).toHaveBeenCalledWith(
                 publicInfoAfterKill, // Send the *updated* public info
                 PlayerStatus.Alive, // Old status
                 PlayerStatus.Dead   // New status
             );
         });

         it('should do nothing if player is already dead', () => {
              const playerIdToKill = villager1Id; // Use actual ID
              game.killPlayer(playerIdToKill, "first kill");
              expect(game.getPlayer(playerIdToKill)?.status).toBe(PlayerStatus.Dead);

              const logCountBefore = game.getConversationLog().getAllMessages().length;
              vi.clearAllMocks(); // Clear mocks associated with renderer

              game.killPlayer(playerIdToKill, "second kill attempt");

              const logCountAfter = game.getConversationLog().getAllMessages().length;
              expect(logCountAfter).toBe(logCountBefore); 
              expect(mockRenderer.renderPlayerStatusUpdate).not.toHaveBeenCalled();
              expect(game.getPlayer(playerIdToKill)?.status).toBe(PlayerStatus.Dead); // Still dead
          });

          it('should do nothing if player ID does not exist', () => {
              const logCountBefore = game.getConversationLog().getAllMessages().length;
              vi.clearAllMocks();

              game.killPlayer('non-existent-player', "attempted kill");

              const logCountAfter = game.getConversationLog().getAllMessages().length;
              expect(logCountAfter).toBe(logCountBefore);
              expect(mockRenderer.renderPlayerStatusUpdate).not.toHaveBeenCalled();
          });
      });
});
